zernikegrams_npz_gz_template: 'training_data/finetuning/rosetta_ddg/premade_zernikegrams/{model_version}.npz.gz'
targets_csv_template: training_data/finetuning/rosetta_ddg/{split}_targets.csv
model_version: hermes_py_000
finetuning_version: ft_ros_ddg_st
finetuning_depth: all
finetune_with_noise: false
batch_size: 128
lr: 0.0005
n_epochs: 4
alpha_cls: 0.0
lr_scheduler: null